Undoing the auto-detection capability
For some reason this is no longer working for me: I'm getting:

ERROR: Command: '/usr/bin/xmllint --xinclude --noout --schema /Users/sacks/cism-code/cism-wrapper/cism-wrapper1/cime/CIME/data/config/xml_schemas/config_machines.xsd /Users/sacks/.cime/config_machines.xml' failed with error '/Users/sacks/.cime/config_machines.xml:4: element NODENAME_REGEX: Schemas validity error : Element 'NODENAME_REGEX': This element is not expected. Expected is ( machine ).
/Users/sacks/.cime/config_machines.xml fails to validate' from dir '/Users/sacks/cism-code/cism-wrapper/cism-wrapper1/cime/scripts'

And if I remove the top-level config_machines.xml and specify the
machine explicitly, I get:

ERROR: No machine green found

I'm not sure why this was working for me before but is no longer
working, but for now I'm backing this out.

See also https://github.com/ESMCI/cime/discussions/4587